logo: # add logo name
title: Catiworks | Traditional & Digital Artist | Illustrator
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Cati!
  ♦ Level 30, Capricorn, 19th january
  ♦Ko-fi doodles
  ♦Harmless hyperball!
  linktr.ee/catiworks
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-pic-hover: face2.png
author-name: Catiworks # your name
about-author: # about author
email: your-email@domain.com # your email
#phone: (496)-169-6557 # your pnone number
website: http://catiworks.com/ # you website

# Social link
google_url: https://linktr.ee/catiworks # add url link
twitter_url: https://www.deviantart.com/catiprojectc  # add url link
instagram_url: https://www.instagram.com/catiworks/# add url link
pinterest_url: https://ko-fi.com/catiworks# add url link
dribbble_url:  https://www.redbubble.com/people/catiworks/shop?asc=u # add url link
facebook_url: https://m.facebook.com/Catiworks/ # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
